### ISSUE TITLE
nbase.arc.pool configuraion Unavailable

### ISSUE THREAD

**Issue by hangsucho** [smallmiro/nbasearc-spring-boot-starter#2]
nbase.arc.pool.initialSize=1
nbase.arc.pool.maxActive=4
nbase.arc.pool.maxIdle=2
nbase.arc.pool.minIdle=2
nbase.arc.pool.maxWait=2

public RedisClusterPoolConfig poolConfig() 에서

poolConfig.setInitialSize( ... 하는 코드가 누락된듯 합니다.

**Comment by smallmiro** [comment]
감사합니다 확인해볼께요..

**Comment by smallmiro** [comment]
다음 빌드에 반영 될예정입니다
